l_french:
 carnx_slave_price_base_desc: "Base"
 carnx_slave_price_claims_desc: "Prétentions"
 carnx_slave_price_dynasty_desc: "Dynastie"
 carnx_slave_price_traits_desc: "Traits"
 carnx_slave_price_skills_desc: "Compétences"
 carnx_slave_price_attraction_desc: "Attirance"
 carnx_slave_price_visibly_fertile_female_desc: "Femme visiblement féconde"
 carnx_slave_price_age_desc: "Âge"
 carnx_slave_price_multiplier_desc: "Multiplicateur d’équilibrage"
 carnx_slave_price_min_desc: "Prix minimum"
 carnx_slave_price_player_desc: "Marge bénéficiaire"
 carnx_slave_price_government_desc: "Gouvernement tribal ou nomade"
 carnx_slave_price_seller_greed_desc: "Avidité du vendeur"
 carnx_slave_price_buyer_greed_desc: "Avidité de l’acheteur"
 carnx_slave_price_seller_attitude_desc: "Attitude esclavagiste du vendeur"
 carnx_slave_price_buyer_attitude_desc: "Attitude esclavagiste de l’acheteur"
 carnx_slave_bid_price_multiplier_desc: "Résultat du marchandage"